### ISSUE TITLE
Not working on current lineage downloader API

### ISSUE THREAD

**Issue by brianjmurrell** [julianxhokaxhiu/LineageOTAUnitTest#1]
https://download.lineageos.org/api/v1/hammerhead/nightly is a 404 now.

**Comment by julianxhokaxhiu** [comment]
That is just a placeholder URL. Nothing really critical, but if you have a suggestion on which is the corrent endpoint officially, feel free to post it here.

**Comment by julianxhokaxhiu** [comment]
Found the culprit, the official API does not work if you don't append the incremental hash in the end, see https://download.lineageos.org/api/v1/hammerhead/nightly/d387428a as an example.

While my REST server does answer, in order to facilitate even old LineageOTA updater where the last incremental hash logic was not yet there.

I'll update the demo to include a demo hash.
